version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - IP_LIMIT=5
      - TOKEN_LIMIT=10
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
