version: '3.8'
services:
  web:
    container_name: web
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./dbdata:/data